---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adhesion-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/going-cloud-native-2023/kubernetes_manifest.git
    path: adhesion-k8s
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default