---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry-service-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/going-cloud-native-2023/kubernetes-manifest.git
    path: edge_k8s/service-registry.yaml
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-gateway-app
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/going-cloud-native-2023/kubernetes-manifest.git
    path: edge-k8s/cloud-gateway.yaml
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default